# -*- coding: utf-8 -*-
from __future__ import annotations

import json
import pickle
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List

import numpy as np

from app.core.exceptions import ArtifactError, InputValidationError
from app.schemas.domain import RawOmicsSample


@dataclass
class PreprocessedOmics:
    patient_id: str
    expression: np.ndarray
    mutation: np.ndarray
    methylation: np.ndarray
    quality_control: Dict[str, Any]


class OmicsPreprocessor:
    def __init__(
        self,
        artifact_dir: Path,
        strict_feature_match: bool = True,
        reject_non_finite: bool = True,
    ) -> None:
        self.artifact_dir = Path(artifact_dir)
        self.strict_feature_match = strict_feature_match
        self.reject_non_finite = reject_non_finite
        self.feature_lists: Dict[str, List[str]] = {}
        self.transformers: Dict[str, Any] = {}
        self.preprocessing_version = None
        self._load()

    def _load_json(self, path: Path):
        with path.open("r", encoding="utf-8") as handle:
            return json.load(handle)

    def _load(self) -> None:
        preprocessing_dir = self.artifact_dir / "preprocessing"
        missing = []
        for modality in ("expression", "mutation", "methylation"):
            feature_file = preprocessing_dir / (modality + "_features.json")
            transformer_file = preprocessing_dir / (modality + "_kpca.pkl")
            if not feature_file.is_file():
                missing.append(str(feature_file))
            if not transformer_file.is_file():
                missing.append(str(transformer_file))
        if missing:
            raise ArtifactError(
                "三组学预处理产物不完整。", {"missing_files": missing}
            )

        for modality in ("expression", "mutation", "methylation"):
            payload = self._load_json(
                preprocessing_dir / (modality + "_features.json")
            )
            features = payload.get("features") if isinstance(payload, dict) else payload
            if not isinstance(features, list) or not features:
                raise ArtifactError(
                    "特征清单格式错误。", {"modality": modality}
                )
            self.feature_lists[modality] = [str(item).strip() for item in features]
            with (preprocessing_dir / (modality + "_kpca.pkl")).open("rb") as handle:
                # Only load pickle artifacts generated by the trusted training pipeline.
                self.transformers[modality] = pickle.load(handle)

        manifest = self.artifact_dir / "metadata" / "data_manifest.json"
        if manifest.is_file():
            self.preprocessing_version = self._load_json(manifest).get(
                "preprocessing_version"
            )

    def transform(self, raw: RawOmicsSample) -> PreprocessedOmics:
        arrays: Dict[str, np.ndarray] = {}
        qc_modalities: Dict[str, Any] = {}

        for modality, parsed in raw.by_modality().items():
            required = self.feature_lists[modality]
            required_set = set(required)
            uploaded = [str(item).strip() for item in parsed.values.index]
            uploaded_set = set(uploaded)
            missing = [item for item in required if item not in uploaded_set]
            extra = [item for item in uploaded if item not in required_set]

            if missing and self.strict_feature_match:
                raise InputValidationError(
                    "上传文件缺少模型要求的特征。",
                    {
                        "model_branch": str(self.artifact_dir),
                        "modality": modality,
                        "missing_feature_count": len(missing),
                        "missing_feature_examples": missing[:20],
                    },
                )

            aligned = parsed.values.reindex(required, fill_value=0.0).to_numpy(
                dtype=np.float64
            ).reshape(1, -1)
            if self.reject_non_finite and not np.isfinite(aligned).all():
                raise InputValidationError(
                    "特征对齐后仍包含NaN或无穷值。", {"modality": modality}
                )

            try:
                transformed = self.transformers[modality].transform(aligned)
            except Exception as exc:
                raise InputValidationError(
                    "组学数据无法通过训练阶段保存的KPCA转换器。",
                    {"modality": modality, "error": str(exc)},
                )

            transformed = np.asarray(transformed, dtype=np.float32).reshape(1, -1)
            arrays[modality] = transformed
            qc_modalities[modality] = {
                "source_filename": parsed.source_filename,
                "detected_orientation": parsed.orientation,
                "uploaded_feature_count": len(uploaded),
                "required_feature_count": len(required),
                "matched_feature_count": len(required) - len(missing),
                "missing_feature_count": len(missing),
                "extra_feature_count": len(extra),
                "missing_feature_examples": missing[:20],
                "extra_feature_examples": extra[:20],
                "final_embedding_dimension": int(transformed.shape[1]),
                "status": "passed" if not missing else "filled_missing_with_zero",
            }

        return PreprocessedOmics(
            patient_id=raw.patient_id,
            expression=arrays["expression"],
            mutation=arrays["mutation"],
            methylation=arrays["methylation"],
            quality_control={
                "required_modalities": ["expression", "mutation", "methylation"],
                "all_three_modalities_received": True,
                "strict_feature_match": self.strict_feature_match,
                "preprocessing_version": self.preprocessing_version,
                "modalities": qc_modalities,
            },
        )
